[project]
name = "pysam"
description = "pysam - a python module for reading, manipulating and writing genomic data sets."
version = "0.20.0"
authors = [
 { name = "Andreas Heger", email = "andreas.heger@gmail.com"}
]
requires-python = ">=3.8"

dependencies = [
    "cython",
]


[build-system]
requires = ["setuptools>=61.0", "wheel", "Cython>=0.29.30,<3.0"]
build-backend = "setuptools.build_meta:__legacy__"